const express = require('express');
const { list, create, update, remove } = require('../controllers/quotationController');
const { authenticate } = require('../middleware/auth');
const router = express.Router();
router.use(authenticate);
router.get('/', list);
router.post('/', create);
router.put('/:id', update);
router.delete('/:id', remove);
module.exports = router;
